version: '3'
services:
  fenics_sim:
    build: .
    container_name: fenics_sim_container
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    ports:
      - "8040:8040"  # Optional: expose ports if needed
